# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 11 Jan 2010 16:19:55 -0700
*               @ALL          1
*               @user         8
