<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: wikiops
 * Date: Sat, 16 Jan 2010 10:42:18 -0700
 */

$conf['title'] = 'Bitlash Online';
$conf['template'] = 'beaufort';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'revisions,register';
$conf['userewrite'] = '1';

// end auto-generated content
